{
    'name': 'Serial Printer Catalog',
    'version': '1.0.0',
    'summary': 'Catálogo de productos sincronizado con API externa',
    'description': 'Sincroniza marcas, productos, variantes, stock, imágenes y precios personalizados desde la API de TopTex.',
    'author': 'Serial Printer',
    'category': 'Sales',
    'depends': ['base', 'product', 'sale', 'stock'],
    'data': [
        'views/menu_root.xml',
        'views/menu_brands.xml',
        'views/brand_views.xml',
        'views/menu_attribute.xml',
        'views/attribute_views.xml',
        'views/menu_variant.xml',
        'views/variant_views.xml',
        'views/menu_product.xml',
        'views/product_views.xml',
        'data/cron_product.xml',
        'data/cron_brand.xml',
        'data/cron_stock.xml',
        'data/cron_images.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}